# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative permalinks are not supported by github pages
# relative_permalinks: true

# Setup
title:               Samsara
tagline:             Lightning fast analytics!
url:                 http://samsara.github.io
paginate:            10
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
# TODO: Extend to add multiple authors.
author:
  name:              Sathyavijayan
  url:               https://twitter.com/sathyavijayan
  email:             sathyavijayan@gmail.com


# Config for Client documentation
# Leading space after page is very important here
tab_bars:
- id: clients
  items:
  - title: iOS
    page: /docs/clients/ios-client/
  - title: Clojure
    page: /docs/clients/clojure-client/
  - title: Logger
    page: /docs/clients/logger-client/

# Markdown and code
markdown:            rdiscount
permalink:           pretty
highlighter:         pygments
